name: GitHub Stats Generator

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: saifyali05
          template: classic
          base: header, community, repositories
          config_timezone: Asia/Kolkata
          filename: metrics.svg
          output_action: commit

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_from: 200

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_load: 300

      - name: Generate classic streak
        uses: DenverCoder1/github-readme-streak-stats@master
        with:
          user: saifyali05
          theme: dark
          hide_border: true
          file: streak.svg
          commit: true
