name: GitHub Stats Generator

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: saifyali05
          template: classic
          base: header, community, repositories
          config_timezone: Asia/Kolkata
          filename: metrics.svg
          output_action: commit

          # Force REST API (fixes activity & habits errors)
        github_api_graphql: disabled


          # Languages
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          # Coding habits
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_from: 200

          # Recent activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_load: 300

          # Classic streak bar
          plugin_streak: yes
          plugin_streak_days: 30
